version: '3'

services:

  harena-manager:
    image: datasci4health/harena-manager:v1
    environment:
      - ENV_SILENT=true      
      - NODE_ENV=production
      - APP_NAME=harena-manager
      - APP_URL=https://harena.ds4h.org
      - CACHE_VIEWS=false
      - APP_KEY=sHuh8734nANKdmasdk31345Kasd
