version: '3'

services:

  harena-manager:
    image: datasci4health/harena-manager:v1
    environment:
      - ENV_SILENT=true      
      - NODE_ENV=production
      - APP_NAME=harena-manager
      - APP_URL=https://dev.harena.ds4h.org/manager
      - CACHE_VIEWS=false
      - APP_KEY=<edit>
    volumes:
      - harena_manager-artifacts:/app/public/resources

volumes:
  harena_manager-artifacts:
    driver: "local"

